title: "libcdaydiff"
desc: "Portable C99 Date & Time Library"
author: "mroczect"
repo_url: "https://github.com/mroczect/libcdaydiff"
license: "GPL-3.0"
site_name: "libcdaydiff"
base_url: "https://mroczect.github.io/libcdaydiff/"
content_dir: "content"
output_dir: "dist"
navbar:
  - label: Home
    url: index.html
  - label: Quick Start
    url: quick-start.html
  - label: API Reference
    url: api-reference.html
  - label: Examples
    url: example.html
  - label: Installation
    url: installation.html
  - label: Contributing
    url: contributing.html
  - label: License
    url: license.html
  - label: Contact
    url: contac.html
sidebar:
  - label: Getting Started
    items:
      - label: Home
        url: index.html
      - label: Quick Start
        url: quick-start.html
      - label: Installation
        url: installation.html
  - label: Documentation
    items:
      - label: API Reference
        url: api-reference.html
      - label: Format Specifiers
        url: format-specifier.html
      - label: Examples
        url: example.html
      - label: Thread Safety
        url: thread-savety.html
  - label: Project
    items:
      - label: Contributing
        url: contributing.html
      - label: License
        url: license.html
      - label: Contact
        url: contac.html
